title: Arka Roy
url: http://arka-nitd.github.io
baseurl: /homepage
description: 'Personal site of Arka Roy, Software Developer @InMobi'
keywords:
 - Arka Roy
 - Arka
plugins:
  - jekyll-textile-converter
author:
    name: Arka Roy
    email: arka.nitdgp14@gmail.com
    twitter: http://twitter.com/arka-nitd
    github: http://github.com/arka-nitd
    facebook: http://www.facebook.com/mailtoarko
    linkedin: http://www.linkedin.com/in/arka-nitd

sections:
 - about
 - research
 - projects
 - blog
stylesheets:
 - /homepage/assets/themes/default/css/screen.css?52480=52480
 - /homepage/assets/themes/default/css/print.css
scripts:
 - http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js    
 - /homepage/assets/themes/default/js/site.js
colors:
    highlights:
        blue: '#009ff7'
        green: '#87d14b'
        red: '#FF007C'
    mono:
        dark: '#000000'
        medium: '#777777'
        light: '#FFFFFF'
    bg: '#EAF1F4'
    
pygments: true
permalink: pretty 
exclude:
 - Rakefile
 - README.markdown
 - .git