title: Arka Roy
url: http://arka-nitd.github.io
description: 'Personal site of Arka Roy, Software Developer @InMobi'
keywords:
 - Arka Roy
 - Arka
plugins:
  - jekyll-textile-converter
author:
    name: Arka Roy
    email: arka.nitdgp14@gmail.com
    twitter: http://twitter.com/arka-nitd
    github: http://github.com/arka-nitd
    facebook: http://www.facebook.com/mailtoarko
    linkedin: http://www.linkedin.com/in/arka-nitd
    avatar: http://www.gravatar.com/avatar/392da320b3aa4068d0b03024135875fb?s=70
    openid:
        server: https://www.google.com/accounts/o8/ud
        delegate: http://www.google.com/profiles/namelessmike
    
sections:
 - projects
 - about
 - journal 
stylesheets:
 - /assets/themes/default/css/screen.css?52480=52480
 - /assets/themes/default/css/print.css
scripts:
 - http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js    
 - /assets/themes/default/js/site.js
colors:
    highlights:
        blue: '#009ff7'
        green: '#87d14b'
        red: '#FF007C'
    mono:
        dark: '#000000'
        medium: '#777777'
        light: '#FFFFFF'
    bg: '#EAF1F4'
    
pygments: true
permalink: pretty 
exclude:
 - Rakefile
 - README.markdown
 - .git